name: Code Check

on:
  pull_request:
    branches: [master, develop]

jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run typecheck

      - name: Prettier Check
        run: pnpm run prettier:check

      - name: Build
        run: pnpm run build
